# Generated by Django 5.1.7 on 2025-06-24 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=255, unique=True)),
                ('data_de_início', models.DateTimeField(default=django.utils.timezone.now)),
                ('prazo_1_em_dias', models.PositiveSmallIntegerField(default=0)),
                ('prazo_2_em_dias', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
