# Generated by Django 5.1.7 on 2025-03-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('prazo', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
