# Generated by Django 5.1.7 on 2025-04-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lista_prazos', '0003_rename_prazo_prazo_prazo_em_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prazo',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
