# Generated by Django 5.1.7 on 2025-04-08 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lista_prazos', '0004_alter_prazo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prazo',
            name='data_de_vencimento',
            field=models.DateTimeField(default=datetime.datetime(1969, 12, 31, 21, 0)),
        ),
    ]
