# Generated by Django 5.1.7 on 2025-04-12 01:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lista_prazos', '0005_prazo_data_de_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prazo',
            name='data_de_vencimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
