# Generated by Django 5.1.7 on 2025-05-06 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lista_prazos', '0007_rename_id_prazo_identificador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prazo',
            old_name='data_de_vencimento',
            new_name='data_de_vencimento_1',
        ),
        migrations.RenameField(
            model_name='prazo',
            old_name='prazo_em_dias',
            new_name='prazo_1_em_dias',
        ),
        migrations.AddField(
            model_name='prazo',
            name='data_de_início',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prazo',
            name='data_de_vencimento_2',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prazo',
            name='prazo_2_em_dias',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
