# Generated by Django 5.1.7 on 2025-06-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lista_prazos', '0008_rename_data_de_vencimento_prazo_data_de_vencimento_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prazo',
            name='data_de_vencimento_1',
        ),
        migrations.RemoveField(
            model_name='prazo',
            name='data_de_vencimento_2',
        ),
    ]
