# Generated by Django 5.1.7 on 2025-06-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lista_prazos', '0009_remove_prazo_data_de_vencimento_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prazo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prazo',
            name='identificador',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
