services:
  web:
    build: .
    image: jopedrop/lista-de-prazos:latest
    container_name: lista-de-prazos
    restart: always
    ports:
      - 8000:8000
    volumes:
      - prazo-data:/app/data
    env_file:
      - .env.prod
volumes:
  prazo-data: