# Generated by Django 5.1.7 on 2025-04-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lista_prazos', '0002_alter_prazo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prazo',
            old_name='prazo',
            new_name='prazo_em_dias',
        ),
    ]
