# Generated by Django 5.1.7 on 2025-04-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lista_prazos', '0006_alter_prazo_data_de_vencimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prazo',
            old_name='id',
            new_name='identificador',
        ),
    ]
