name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jopedrop/lista-de-prazos:latest
    - name: Push the image to Docker Hub
      run: docker push jopedrop/lista-de-prazos:latest
