name: Docker Image CI

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jopedrop/lista-de-prazos:latest
    - name: Push the image to Docker Hub
      run: |
        docker login -u jopedrop -p ${{ secrets.DOCKER_HUB_TOKEN }} 
        docker push jopedrop/lista-de-prazos:latest
